name: CI Pipeline   # This gives a name to the workflow.

on:                 # This tells GitHub when the workflow should start.
  push:             # Whenever code is uploaded to GitHub.
    branches:
      - main        # Run the workflow only if code is pushed to the main branch.

jobs:               # A job is a collection of tasks.
  build:            # Job name.
    runs-on: ubuntu-latest   # GitHub creates a temporary Ubuntu Linux virtual machine.

    steps:          # Every task is written here.
      - name: Checkout Repository
        uses: actions/checkout@v4   # Downloads the repository into the Ubuntu machine.

      - name: Display Welcome Message
        run: echo "Continuous Integration Started"   # Executes a Linux command.

      - name: Display Current Directory
        run: pwd   # Prints the current working directory.

      - name: List Repository Files
        run: ls    # Lists all files in the repository.

      - name: Display Completion Message
        run: echo "Pipeline Executed Successfully"   # Prints the completion message.
